version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  api:
    build: 
      context: ./backend
    container_name: flowbit-api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://localhost:27017/flowbit
      - JWT_SECRET=super-secret
      - N8N_SECRET=shared-n8n-secret
    networks:
      - flowbit-net
    depends_on:
      - n8n
      - mongo
    volumes:
      - ./backend:/app
    command: >
      sh -c "npm run dev"
  

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - WEBHOOK_TUNNEL_URL=http://localhost:4040  # for ngrok dev
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - flowbit-net

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    command: http n8n:5678
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=302AJ8QLo0xtmQlRxhFAEf8FDb4_JE8QgQVKghQpALwobEDU
    depends_on:
      - n8n
    networks:
      - flowbit-net

  shell:
    build:
      context: ./frontend/shell     
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/shell:/app
      - /app/node_modules


  supportticketsapp:
    build:
      context: ./frontend/mfes/supporttickets
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./frontend/mfes/supporttickets:/app
      - /app/node_modules

volumes:
  mongo-data:
  n8n-data:

networks:
  flowbit-net:
    driver: bridge